# Generated by Django 5.0.3 on 2024-03-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('worker_name', models.CharField(max_length=30)),
                ('task_description', models.CharField(max_length=30)),
                ('time_to_complete', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='name',
            old_name='time_to_complete',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='name',
            name='task_owner',
            field=models.ManyToManyField(blank=True, to='main.tasks'),
        ),
    ]
