# Generated by Django 5.0.3 on 2024-03-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tasks_rename_time_to_complete_name_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
