# Generated by Django 5.0.3 on 2024-03-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='contact',
            new_name='ttc',
        ),
    ]
