# Generated by Django 5.0.3 on 2024-03-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='task_owner',
        ),
    ]
