# Generated by Django 5.0.3 on 2024-03-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_name_task_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='first_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='last_name',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='contact',
            new_name='time_to_complete',
        ),
    ]
