# Generated by Django 5.0.3 on 2024-03-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_task_description_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, default='1/1/1970'),
        ),
    ]
