# Generated by Django 5.0.3 on 2024-03-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_contact_name_ttc'),
        ('main', '0005_rename_first_name_name_description_and_more'),
    ]

    operations = [
    ]
