# Generated by Django 5.0.3 on 2024-03-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default='1/1/1970'),
        ),
        migrations.AlterField(
            model_name='name',
            name='first_name',
            field=models.CharField(default='John', max_length=30),
        ),
        migrations.AlterField(
            model_name='name',
            name='last_name',
            field=models.CharField(default='Doe', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='help', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='work', max_length=30),
        ),
    ]
