# Generated by Django 5.0.3 on 2024-03-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_task_assigned_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='email',
        ),
    ]
