# Generated by Django 5.0.3 on 2024-03-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_name_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='phone',
            new_name='column3',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='column2',
        ),
    ]
